### PR TITLE
Resolve #5

### LINKED ISSUE #5: Client cannot subscribe to multiple channels at the same time
The Client cannot subscribe to more than one channel without a minimum of 2 calls to the process() method in between the calls in order to process the incoming SCRB_RSP. The following snippet will fail to do what is expected:

```cpp
void setup()
{
    gYapClient.subscribeToChannel("TEST1", CB1);
    gYapClient.subscribeToChannel("TEST2", CB2);
}
```
This client would only try to subscribe to TEST2, as the m_pendingSuscribeChannel member would be overwriten on the second call to the method.

Currently I do not have a clean solution for this issue. (Should this be converted to a Github Issue?)

The first idea to come to mind is to use an array to hold a determined number of pending channels to suscribe to. However this raises other problems such as memory usage and how to track which channels are suscribed and which are still pending, and when/where does the suscribing process takes places.

_Originally posted by @gabryelreyes in https://github.com/BlueAndi/RadonAlcer/pull/2#discussion_r1167249830_

Keep in mind that the response may never come.

### PR DESCRIPTION
**Pull request by gabryelreyes**
Pending subscribe channels are stored in a separate array of size tMaxChannels.
Once a response for the pending channel is received, it is moved to the data channels array.

SCRB_RSP includes the name of the Channel to help identify the correct callback in the pending array.

### CODE REVIEW

File: lib/Service/YAPServer.hpp [hunk 1]
```diff
@@ -235,16 +233,35 @@ class YAPServer
     }
 
     /**
-     * Get the number of configured channels.
+     * Get the number of configured TX channels.
      * @returns Number of configured Data Channels. The Command Channel is ignored here.
      */
-    uint8_t getNumberOfChannels()
+    uint8_t getNumberOfTxChannels()
```
Comment (BlueAndi) [inline lib/Service/YAPServer.hpp:239]: getNumberOfTxChannels clones getNumberOfRxChannels. Do we need the logic or is it easier with less space to use a member variable, counting at registration or successful subscription?

**Review by BlueAndi — APPROVED** [review]
